### ISSUE TITLE
Add RK855

### ISSUE THREAD

**Issue by syfq91** [rnayabed/rangoli#1]
Hi,

First of all, awesome project.

Is it possible to add support for RK855? My keyboard is working fine when connected to Ubuntu 22.10, but rangoli does not detect it.

Here is dmesg log when connecting the keyboard:
```
[  630.445163] usb 2-1.2: new full-speed USB device number 5 using ehci-pci
[  630.556549] usb 2-1.2: New USB device found, idVendor=0c45, idProduct=8018, bcdDevice= 1.12
[  630.556615] usb 2-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  630.556622] usb 2-1.2: Product: USB DEVICE
[  630.556627] usb 2-1.2: Manufacturer: SONiX
[  630.560284] input: SONiX USB DEVICE as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.2/2-1.2:1.0/0003:0C45:8018.0003/input/input21
[  630.619122] hid-generic 0003:0C45:8018.0003: input,hidraw0: USB HID v1.11 Keyboard [SONiX USB DEVICE] on usb-0000:00:1d.0-1.2/input0
[  630.621781] input: SONiX USB DEVICE Consumer Control as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.2/2-1.2:1.1/0003:0C45:8018.0004/input/input22
[  630.681922] input: SONiX USB DEVICE System Control as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.2/2-1.2:1.1/0003:0C45:8018.0004/input/input23
[  630.682661] input: SONiX USB DEVICE Keyboard as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.2/2-1.2:1.1/0003:0C45:8018.0004/input/input24
[  630.683330] input: SONiX USB DEVICE Mouse as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.2/2-1.2:1.1/0003:0C45:8018.0004/input/input25
[  630.684462] input: SONiX USB DEVICE as /devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.2/2-1.2:1.1/0003:0C45:8018.0004/input/input26
[  630.686330] hid-generic 0003:0C45:8018.0004: input,hiddev0,hidraw1: USB HID v1.11 Keyboard [SONiX USB DEVICE] on usb-0000:00:1d.0-1.2/input1
```

**Comment by rnayabed** [comment]
Thank you so much for using Rangoli and reporting this issue.

Can you share the link of the official RK software that supports this keyboard?

**Comment by syfq91** [comment]
Here the product page:
https://rkgamingstore.com/collections/65-keyboards/products/rk68-68-wireless-gaming-keyboard?variant=42755018064093

You can download the software from here:
https://drive.google.com/file/d/1sq4vglRZ-76aPoszcGp4_uBD27Kvu7Oo/view

**Comment by rnayabed** [comment]
https://github.com/rnayabed/rangoli/releases/download/2.0-rc/rangoli-portable-linux-64.zip

Can you try this?

**Comment by syfq91** [comment]
Hi, I downloaded 2.0-rc build.
then run these command:
```
chmod +x rangoli
./rangoli
```

It asked for password for udev-rules-writer, then is shows this error.
![Screenshot from 2023-02-23 18-01-06](https://user-images.githubusercontent.com/14043220/220877477-20310b4c-65be-4c69-b8a1-b5877f3fa70c.png)

**Comment by rnayabed** [comment]
I made some changes to the way keyboard info is stored and forgot to update the udev script..

**Comment by rnayabed** [comment]
Try again with the new build:

https://github.com/rnayabed/rangoli/releases/download/2.0-rc/rangoli-portable-linux-64.zip

Also, please do the following:
1. Download hidapitester from here https://github.com/todbot/hidapitester/releases/tag/0.2
2. Extract, and run this command:
3. `<path to hidapitester>/hidapitester --vidpid 0c45:8018 --list-detail`
4. send output here

**Comment by syfq91** [comment]
I tried another build, no more error about udev. but it still does not detect the keyboard.

Here the hidapitester output:
```
0C45/8018: SONiX - USB DEVICE
  vendorId:      0x0C45
  productId:     0x8018
  usagePage:     0x0001
  usage:         0x0006
  serial_number:  
  interface:     0 
  path: /dev/hidraw0

0C45/8018: SONiX - USB DEVICE
  vendorId:      0x0C45
  productId:     0x8018
  usagePage:     0x000C
  usage:         0x0001
  serial_number:  
  interface:     1 
  path: /dev/hidraw1

0C45/8018: SONiX - USB DEVICE
  vendorId:      0x0C45
  productId:     0x8018
  usagePage:     0x0001
  usage:         0x0080
  serial_number:  
  interface:     1 
  path: /dev/hidraw1

0C45/8018: SONiX - USB DEVICE
  vendorId:      0x0C45
  productId:     0x8018
  usagePage:     0x0001
  usage:         0x0006
  serial_number:  
  interface:     1 
  path: /dev/hidraw1

0C45/8018: SONiX - USB DEVICE
  vendorId:      0x0C45
  productId:     0x8018
  usagePage:     0x0001
  usage:         0x0002
  serial_number:  
  interface:     1 
  path: /dev/hidraw1

0C45/8018: SONiX - USB DEVICE
  vendorId:      0x0C45
  productId:     0x8018
  usagePage:     0x0001
  usage:         0x0001
  serial_number:  
  interface:     1 
  path: /dev/hidraw1

0C45/8018: SONiX - USB DEVICE
  vendorId:      0x0C45
  productId:     0x8018
  usagePage:     0xFFFF
  usage:         0x0001
  serial_number:  
  interface:     1 
  path: /dev/hidraw1
```

**Comment by rnayabed** [comment]
Yet another bug found, sorry 😭

**Comment by rnayabed** [comment]
Builds have been updated. Please check again

**Comment by syfq91** [comment]
Hi, tested the newer build, it still not detected.
Please let me know if you need more info.

**Comment by rnayabed** [comment]
Try again by re downloading, should work now

https://github.com/rnayabed/rangoli/releases/tag/2.0-rc

**Comment by syfq91** [comment]
Hi, now it detects the keyboard. But there’s a permission error. It cannot save any changes. 
![rangoli rk855](https://user-images.githubusercontent.com/14043220/221863232-f39ba44b-f7db-4fe4-ba04-0e34a55ade4c.png)

**Comment by rnayabed** [comment]
Do the following:
1. Download [hidapitester](https://github.com/todbot/hidapitester/releases/tag/0.2)
2. Run `<file path to hidapitester.exe> --vidpid 0c45:8018 --list-detail`
3. It will print a list of blocks, with `paths`. 
4. Take each `path` and run the following command `<file path to hidapitester.exe> --open-path "<EACH PATH>" --length 65 --send-feature 0x0a,0x01,0x01,0x02,0x29,0x01,0x03,0x03,0x03,0,0,0,0x01,0x01`
5. Note when the keyboard flickers or atleast changes colour. I think it should be the one with `...&col03...`. Send the full path here.

**Comment by rnayabed** [comment]
Also, RK855 is RGB right?

**Comment by rnayabed** [comment]
Ok, so it looks like this keyboard is the same as RK68K (?). Same VID/PID.

However it seems like rk68k is blue backlight only, while i am not sure if rk855 is rgb or not. please confirm

**Comment by syfq91** [comment]
Hi,

RK855 is not RGB, only blue LED.

Here are the output for hidapitester from Ubuntu:
`./hidapitester  --vidpid 0c45:8018 --list-detail`

```
0C45/8018: SONiX - USB DEVICE
  vendorId:      0x0C45
  productId:     0x8018
  usagePage:     0x0001
  usage:         0x0006
  serial_number:  
  interface:     0 
  path: /dev/hidraw0

0C45/8018: SONiX - USB DEVICE
  vendorId:      0x0C45
  productId:     0x8018
  usagePage:     0x000C
  usage:         0x0001
  serial_number:  
  interface:     1 
  path: /dev/hidraw1

0C45/8018: SONiX - USB DEVICE
  vendorId:      0x0C45
  productId:     0x8018
  usagePage:     0x0001
  usage:         0x0080
  serial_number:  
  interface:     1 
  path: /dev/hidraw1

0C45/8018: SONiX - USB DEVICE
  vendorId:      0x0C45
  productId:     0x8018
  usagePage:     0x0001
  usage:         0x0006
  serial_number:  
  interface:     1 
  path: /dev/hidraw1

0C45/8018: SONiX - USB DEVICE
  vendorId:      0x0C45
  productId:     0x8018
  usagePage:     0x0001
  usage:         0x0002
  serial_number:  
  interface:     1 
  path: /dev/hidraw1

0C45/8018: SONiX - USB DEVICE
  vendorId:      0x0C45
  productId:     0x8018
  usagePage:     0x0001
  usage:         0x0001
  serial_number:  
  interface:     1 
  path: /dev/hidraw1

0C45/8018: SONiX - USB DEVICE
  vendorId:      0x0C45
  productId:     0x8018
  usagePage:     0xFFFF
  usage:         0x0001
  serial_number:  
  interface:     1 
  path: /dev/hidraw1
```

/dev/hidraw0 output:
```
Opening device. path: /dev/hidraw0
Writing 65-byte feature report...wrote 65 bytes:
 0A 01 01 02 29 01 03 03 03 00 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 00
Closing device
```

/dev/hidraw1 output:
```
Opening device. path: /dev/hidraw1
Writing 65-byte feature report...wrote -1 bytes:
 0A 01 01 02 29 01 03 03 03 00 00 00 01 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 00
Closing device
```

I don't see any differences on the keyboard when running both path.

Do I need to check using Windows? If yes, I can test it in a few days.

**Comment by rnayabed** [comment]
Yes, please check on windows as well. 
I am closing this issue, merging it with #13 
Please post replies there
