### ISSUE TITLE
[MacOS] RK71 (0x258a:0x0069) not detected

### ISSUE THREAD

**Issue by dattapw** [rnayabed/rangoli#15]
I've installed the MacOS installer app. On opening the app it shows Unable to open keyboards list. I saw that the issue was resolved but I guess it was not compiled into a release. Can you please update the release binaries? Thanks.

OS: MacOS Monterey
Keybaord: RK71

**Comment by rnayabed** [comment]
Hi, 1.0 macos is broken. I'll shortly put it as a notice.

Use 2.0-rc for the time being, please.

https://github.com/rnayabed/rangoli/releases/tag/2.0-rc

Remember to run 
```
xattr -dr com.apple.qurantine <path to rangoli.app>
```
 before running.

**Comment by dattapw** [comment]
Now it's not detecting the keyboard. Mine is an RK71 dual mode. I tried both in wired and wireless mode. Thanks for the help.

[https://i.imgur.com/tQTmSXs.png](https://i.imgur.com/tQTmSXs.png)
[https://i.imgur.com/j5t07mf.png](https://i.imgur.com/j5t07mf.png)

**Comment by rnayabed** [comment]
Provide the vid and pid please

**Comment by dattapw** [comment]
RK71RGB-3.0:
  Vendor ID:	0xAE24
  Product ID:	0x8918
  Firmware Version:	0.0.1
  Minor Type:	Keyboard
  Services:	0x800020 < HID ACL >

**Comment by dattapw** [comment]
RK71RGB-5.0:
Address:	FC:AE:EF:BB:BE:54
Minor Type:	Keyboard
Services:	0x400000 < BLE >

**Comment by dattapw** [comment]
The keyboard has Bluetooth 5.0 and 3.0 connections.

**Comment by dattapw** [comment]
On wired mode:

RK Bluetooth Keyboar:

  Product ID:	0x0069
  Vendor ID:	0x258a
  Version:	30.01
  Speed:	Up to 12 Mb/s
  Manufacturer:	SINO WEALTH
  Location ID:	0x14310000 / 2
  Current Available (mA):	500
  Current Required (mA):	500
  Extra Operating Current (mA):	0

**Comment by rnayabed** [comment]
Thank you, I will share a build soon with proper logging so that I can understand what is going on.

**Comment by rnayabed** [comment]
Please try the new 2.0-rc builds

**Comment by rnayabed** [comment]
https://github.com/rnayabed/rangoli/releases/tag/2.0-rc

**Comment by rnayabed** [comment]
Since, you have closed the issue, I assume it fully works on macos?

**Comment by dattapw** [comment]
Yup
