### ISSUE TITLE
Support for Akko keyboard

### ISSUE THREAD

**Issue by mertgibi** [rnayabed/rangoli#31]
I am using Akko 3068B multimode. Its software is not stable.

Can you add support for this keyboard?

**Comment by rnayabed** [comment]
I don't have the keyboard, if you want, you can contribute the relevant pcap files/protocol, or consider donating funds so that i can purchase the keyboard.

**Comment by mertgibi** [comment]
I already have a keyboard. If you give a little information on how to do it, I can contribute.

**Comment by rnayabed** [comment]
The idea is to record communication between your computer and keyboard. You can do this using Wireshark and USBPcap (bundled together).

After that you can record the steps/changes that you did, and corresponding data that is sent between each change. then you can compare each bytes sent and you can deduce patterns, etc for each change :)
