### ISSUE TITLE
support for redragon keyboards

### ISSUE THREAD

**Issue by Arnab11** [rnayabed/rangoli#32]
I would like to know do you have any plans to include support for redragon keyboards like k617 fizz or K630 etc. ?

**Comment by rnayabed** [comment]
Paisa de bhau abhi banake deta hu

**Comment by Arnab11** [comment]
bro, samajh ne ki kosish kro, paisa hota toh kab ka royal kludge ka keyboard kharid leta...

**Comment by rnayabed** [comment]
bhai jodi red dragon keyboard pae ak din/ keo donate kore/keo contribute kore tokhon dekha jabe
