### ISSUE TITLE
Add RK71 3 mode

### ISSUE THREAD

**Issue by badmark** [rnayabed/rangoli#5]
HID/PID 05ac:024f

Royal Kludge RK71 3 mode circa 2021. Works in RK software not detected in Linux or Windows using Rangoli.

**Comment by rnayabed** [comment]
Please Share link of rk software that works with this

**Comment by badmark** [comment]
Here you go: https://drive.google.com/file/d/1WX9xsanvjScnr6xXaVmyndV9L2m3vtJn/view?usp=sharing

**Comment by aravindh-murugesan** [comment]
I might have the same keyboard, the hotswappable wired/wireless variant with Brown switches and it does not detect mine as well. It says unable to open the keyboard list.

**Comment by rnayabed** [comment]
Try this
https://github.com/rnayabed/rangoli/releases/tag/2.0-rc

**Comment by rnayabed** [comment]
> I might have the same keyboard, the hotswappable wired/wireless variant with Brown switches and it does not detect mine as well. It says unable to open the keyboard list.

Unable to open keyboard list was a mac issue that has been resolved #6 

Future builds will not have this issue
