### ISSUE TITLE
support for RK R65 wired full RGB

### ISSUE THREAD

**Issue by kronfusion** [rnayabed/rangoli#83]
so on the rk website there is no software for this keyboard but i emailed the RK people and they sent me a software which works with this keyboard.  it looks similar to the rk61 or rk74 software also the VID is - 258a but the PID is 0172. software size is too big for me to upload here. also on the rk website in the qmk firmware section theres a firmware for RK R65 wired but the json file in that folder has different VID and PID than the keyboard.
[20240126160433_2716.zip](https://github.com/rnayabed/rangoli/files/14442363/20240126160433_2716.zip) -- this is the firmware thats on the rk website. please help if u can, thanks!

**Comment by sfzaw** [comment]
#76 duplicate thread
